### ISSUE TITLE
Differences compared to `lukas-reineke/virt-column.nvim`

### ISSUE THREAD

**Issue by hinell** [xiyaowong/virtcolumn.nvim#4]
What is the difference compared to `lukas-reineke/virt-column.nvim` plugin?

**Comment by xiyaowong** [comment]
@hinell 
- Zero configuration. That's why a separate repository.
- Better performance. This avoids a lot of unnecessary repainting.
- ![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/47070852/10a3b7e2-24f2-4fb3-a8f9-38d96aa95dd4) ![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/47070852/47162d40-2f53-4b3f-b724-59ee881d7061)

**Comment by hinell** [comment]
@xiyaowong Please, write this into your README.md

Thanks!

**Comment by hinell** [comment]
@xiyaowong Please, write this into your README.md
BTW, have you done benchmarking?
